version: '3.3'

services:
  application_server:
    image: node:latest
    container_name: application-server
    working_dir: /application-server
    volumes:
      - .:/application-server
    links:
      - mysql
      - redis
      - socket_server
    command: bash -c "npm install && npm run prod:docker"
    ports:
      - '8001:8001'
    expose:
      - '8001'
  socket_server:
    image: node:latest
    container_name: socket-server
    working_dir: /socket-server
    volumes:
      - ./socket-server:/socket-server
    links:
      - mysql
      - redis
    command: bash -c "npm install && npm run prod:docker"
    ports:
      - '9001:9001'
    expose:
      - '9001'
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'chat'
      MYSQL_USER: 'chat'
      MYSQL_PASSWORD: 'INjQSFVmPm'
      MYSQL_ROOT_PASSWORD: '6pLWmEE4R7'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - chat:/var/lib/mysql
  redis:
    image: redis:alpine
    container_name: cache
    ports:
      - '6380:6379'
    expose:
      - '6380'
volumes:
  chat: